### ISSUE TITLE
Huge Data Table 

### ISSUE THREAD

**Issue by mictadlo** [dc-js/dc.js#101]
Hello,
In case a Data Table contains a lot of data. Would it be possible that it automatically split the data on different pages? Similar like ebay does it with search results:

Page 1 of 20	|  < Previous 1 2 3 4 5 6 7 Next > | Items per page 25  | 50  | 100  | 200

Thank you in advance.

**Comment by gordonwoodhull** [comment]
Porting the `beginSlice`, `endSlice` functionality from dataGrid so that we have basic (manual) pagination support. 

Since the dataTable is only is supposed to support basic table support, I think this is almost enough. As noted above, it's still going to be slow if there is lots and lots of data, but there doesn't seem to be a way around it with crossfilter and usually slowness comes from the DOM rather than the data.

It might be nice to add basic UI support as well - I'll open a separate issue for that.

**Comment by gordonwoodhull** [comment]
Adding example http://dc-js.github.io/dc.js/examples/table-pagination.html
