### ISSUE TITLE
Coordinate System and content misalign in bar charts

### ISSUE THREAD

**Issue by MatthiasJobst** [dc-js/dc.js#1040]
Currently I have two bar charts which show different views of the same data. When one chart is filtered either by brushing or by selecting a bar and then reset something strange happens: The coordinate system and the bars start to misalign. Specifically in my example the x-Axis starts moving up every time.
Here is a fiddle that shows the effect: https://jsfiddle.net/MatthiasJobst/2ocxtzy5/16/
The image shows how it looks like after several iterations.
![bildschirmfoto 2015-11-16 um 21 23 19](https://cloud.githubusercontent.com/assets/15877064/11193687/5deacc4c-8ca8-11e5-993b-5a6130e8efa0.png)
This does not happen in 1.7.5, but in 2.0.0 betas 19 and up.

**Comment by gordonwoodhull** [comment]
Hi @MatthiasJobst, thanks for the report. This looks like it might be the same as #980, but I haven't been able to reproduce that or generate a test case. 

We have done some work since around beta 14 to improve the resizing / responsive behavior. But the code is complicated and there certainly may be bugs.

Is there any chance you can produce a fiddle or something else I can try out to debug where the issue lies?

**Comment by MatthiasJobst** [comment]
Actually in the issue report there is a fiddle link included. Let me know if you cannot access it and I can paste the code here. It is a minimal example.

**Comment by gordonwoodhull** [comment]
Sorry, don't know how I missed that. 

That is very helpful, thanks!

**Comment by MatthiasJobst** [comment]
Reading through the discussion in  #980 setting the .height attribute provides a fix to the problem.

**Comment by gordonwoodhull** [comment]
Glad to hear it. I'm glad the workaround works but it's still a bug. I'm going to merge this into #980 and continue the discussion there.
