### ISSUE TITLE
Stacked line charts not aligned with values on Y axis

### ISSUE THREAD

**Issue by jzheng2015** [dc-js/dc.js#1042]
I may read wrong or not clearly understand the content. When moving mouse over the stacked orange area (Monthly Index Move), you will see the crosshairs to the Y axis mismatched with the value (shown in tooltip) from the orange area. The blue area (Monthly Index Average) looks correct to me but not the stacked orange area. Is this a bug or my reading wrong?  Please see the stacked line chart here on the coordinated-views: http://dc-js.github.io/dc.js/

Thanks!

**Comment by alan-unravel** [comment]
They seem fine to me. You could be associating two points on the orange and blue stack that don't actually come together but are just close on the x-axis

**Comment by gordonwoodhull** [comment]
Thanks for the report @jzheng2015.

It looks correct to me too. I think what you are probably seeing is that the tooltip shows the value for the orange area, not the total (orange + blue). So yes, the number is different, because it is measuring something different.

Please comment if this still doesn't make sense. 

[Conceivably the tooltip could also show the total, although TBH I am not sure what this chart is measuring, since the absolute value of the move is taken and then stacked on the average. So I'm not sure that the total is a useful measure.]
