### ISSUE TITLE
xAxis date series on seriesChart shows Month name instead of day of the week

### ISSUE THREAD

**Issue by Palakila** [dc-js/dc.js#1078]
I am using the new seriesChart for a time series chart and every time the day of the week being plotted is a sunday, a month name is shown instead. For example for a week that goes thru sunday in the month of december, you would see 'Fri 18, Sat 19, Dec 20, Mon 21, Tue 22' and so forth. I am using the latest 2.5 bits from https://github.com/dc-js/dc.js/blob/1fdd7f73aec3964131da1914c40387a6458d62a3/dc.js .

![dc-date-issue](https://cloud.githubusercontent.com/assets/15808414/12029141/c046baf2-ad98-11e5-99a5-f62f13398d04.jpg)

[HTMLPage-Series-Example.txt](https://github.com/dc-js/dc.js/files/73699/HTMLPage-Series-Example.txt)

**Comment by gordonwoodhull** [comment]
Hi, this is a general question about d3.axis, nothing particular about dc.js. 

See for example this question on SO: 
http://stackoverflow.com/questions/26831783/why-are-the-labels-on-my-d3-axis-inconsistent-e-g-month-day

You can more tightly control the tick labels using [d3.axis.tickFormat](https://github.com/mbostock/d3/wiki/SVG-Axes#tickFormat)

If you can't figure it out, please follow up [on Stack Overflow with the dc.js tag](http://stackoverflow.com/questions/tagged/dc.js), or [on the user group](https://groups.google.com/forum/?fromgroups=#!forum/dc-js-user-group), since this is a support question and not an issue or a feature request.

**Comment by Palakila** [comment]
Perfect. Thanks!
