### ISSUE TITLE
tooltip on stacked bar chart

### ISSUE THREAD

**Issue by alsguimaraes** [dc-js/dc.js#1087]
Congratulations on such great software!

There seems to be a bug on the stacked bar chart tooltip. 
Note the basic example on the dc.js page. 

http://dc-js.github.io/dc.js/examples/stacked-bar.html

The selection of a bar on each stack always shows the value for the first group.  
I could not find a workaround, as I do not know how to identify on the tooltip function which stack is being highlighted/selected. 
For now, I forced the tooltip function to show all values. But this is still not ideal, as only one stack is selected.

-Andre

**Comment by alan-unravel** [comment]
The reason that happens is that the separate stacks all use the same key and get the title from the chart group and not the stacks. You can probably fix it using a renderlet that selects each stack and creates the titles accordingly for  each stack.

**Comment by gordonwoodhull** [comment]
You can use `this.layer` to determine the current stack, but that's an accident of the implementation using `dc.pluck`. Or you can set individual title functions for each stack [using the specialized version of `.title()` in the stack mixin](https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#dc.stackMixin+title).

**Comment by gordonwoodhull** [comment]
I'm fixing the example by using `this.layer`, which is perhaps cheating but at least it works.

In a way this is an instance of the inconsistency in #703 - in a lot of cases it's more useful to have the "outer datum" rather than just the data from the group. I believe this is why some charts supply one and some supply the other. I consider this problem a vote for the outer datum.
