### ISSUE TITLE
html docs could start on dc namespace

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1103]
It's okay to have `html/dc.html` be the start page, but it would be better if html/index.html went to the same place, because landing on a blank page is unnerving.

**Comment by mtraynham** [comment]
Not sure why it generates an empty index page in the first place... but let's do this instead.

Gordon, I'll let you make the change since it's basically a one-liner.

In `Gruntfile.js`:
```
        jsdoc: {
            dist: {
                src: [ '<%= conf.src %>/**/*.js', '!<%= conf.src %>/{banner,footer}.js'],
                options: {
                    destination: 'web/docs/html',
                    template: 'node_modules/ink-docstrap/template',
                    configure: 'jsdoc.conf.json'
                }
            }
        },
```

Change the `src` array to include the `README.md` file:
`src: ['README.md', '<%= conf.src %>/**/*.js', '!<%= conf.src %>/{banner,footer}.js'],`

**Comment by gordonwoodhull** [comment]
Ok, cool, that works.
