### ISSUE TITLE
coloring scatterPlot problem of ordering of symbols

### ISSUE THREAD

**Issue by PBrockmann** [dc-js/dc.js#1107]
When 2 symbols share the same coordinates then only one is visible.
Even with a opacity set at 0.5, you cannot see both symbols.
However they are there and can be seen with you play with filtering.

I have prepare a jsfiddle to demonstrate this problem
https://jsfiddle.net/PBrockmann/81mzjkjz/

Could someone confirm it ?
Tested with last dc 2.0.0-beta.26

**Comment by gordonwoodhull** [comment]
As discussed on gitter, this was a data issue. 

There is still a visibility problem since the change of color is not very obvious: 
https://jsfiddle.net/gordonwoodhull/c593ehh7/5/

Generally color blending is not an obvious way to see "there are two things here". But besides adding jitter, I can't think of a good solution.

I'm closing this. Please comment if there is still an issue.

**Comment by PBrockmann** [comment]
Thanks a lot.
