### ISSUE TITLE
How do charts know how to update themselves?

### ISSUE THREAD

**Issue by lmatteis** [dc-js/dc.js#1126]
Let's say I have a chart with a specific dimension and group, such as:

```
var gender = xf.dimension(function (d) { return d.gender; }),
    genders = gender.group().reduceSum(function (d) { return d.interactions; })
```

Then I have another chart, which when interacted with (perhaps a pie chart click), it alters the first chart. How does the first chart know that it needs to update based on the value click on the pie chart? I'd imagine it must somehow know about the `interactions` property in order to rerun the reduce function such as:

```
// this runs inside the chart
group = group.reduceSum(function (d) {
  if (d.key == valueClicked) return d.interactions;
  else return 0;
})
```

Do interactions in DC.js actually involve rerunning the reduce functions or does it do it in some other way?

**Comment by gordonwoodhull** [comment]
It's quite simple on the dc.js side, actually. When the filter on crossfilter changes, all the groups get recalculated. This only requires reducing whatever rows have entered or left each bin.

Then communication between the charts is just a broadcast "redraw" via the chart registry.

https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#dc.chartRegistry

(I'm not going to try to explain the crossfilter magic that allows it to do a minimal recalculation, that part is not so simple.)

**Comment by lmatteis** [comment]
Interesting and how do you know which "rows" have entered/left a bin (what's a "bin" in this context?)?

**Comment by gordonwoodhull** [comment]
Ummm, I was trying to answer the dc.js question without getting into the mechanics of crossfilter, but let me just give one example. I don't promise to be very accurate or thorough, because crossfilter internals are complicated.

I use the word "bin" in the histogram sense, to refer to one of the categories within a group, because there doesn't seem to be a standard term for that. 

So say that the current filter on one of the dimensions is the range 1->5 and it is expanded to 1->6. Internally the crossfilter dimension keeps track of all the rows that mapped to the key 6. 

Crossfilter checks which of these rows also pass all the other filters on all the other dimensions. Then it tells all of the other dimensions to add those rows. 

Then the other dimensions use their own internal maps to determine which groups those rows belong to, and they tell their groups to reduceAdd those rows.

Etc, etc. It isn't magic but it's complicated and all done very efficiently.

At one point I tried to write something up about how crossfilter works but it ended up being more a walkthrough of the code than a comprehensible explanation.

**Comment by lmatteis** [comment]
I did not know that calling `dimension.filter()` for one dimension would also change other groups! Wish this was better documented on crossfilter's site!!

**Comment by gordonwoodhull** [comment]
In fact, one dimension's filter will *only* change the groups on *other* dimensions, and not the groups on that dimension. It's documented, but the documentation is very terse.

> Note: a grouping intersects the crossfilter's current filters, except for the associated dimension's filter. Thus, group methods consider only records that satisfy every filter except this dimension's filter. So, if the crossfilter of payments is filtered by type and total, then group by total only observes the filter by type.

https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_group

I'm going to close this, because there isn't really a dc.js request here. But hopefully this will help others.
