### ISSUE TITLE
Help is making line chart with no map reduce opeartion

### ISSUE THREAD

**Issue by rohit-guitar** [dc-js/dc.js#1139]
Hello ,

I have computed data which doesn't require map reduce operations. I am just trying to make a line chart using dc.js. I couldn't figure out how to put data on y axis. 

dataset 
[{y:12,x=1},{y:20,x=2},......]

code:- 
  var ndx = crossfilter(dataSet);

        //define dimensions
        var xaxis = ndx.dimension(function(d) {
          return d.x;
        });

        var top = xaxis.top(1)[0].x;
        var bottom = xaxis.bottom(1)[0].x;

        //Metrices
        var yaxis = ndx.dimension(function(d) {
          return d.y;
        });

        var exp = xaxis.group().reduce(function(d){
            console.log(d);
        });

        chart
        .width(600)
          .height(220)
          .margins({
            top: 10,
            right: 50,
            bottom: 30,
            left: 50
          })
          .dimension(xaxis)
          .group(yaxis)
          .renderArea(true)
          .transitionDuration(500)
          .x(d3.scale.linear().domain([bottom,top]))
          .elasticY(true)
          .renderHorizontalGridLines(true)
          .renderVerticalGridLines(true)
          .xAxisLabel("Test")
          .yAxis().ticks(6);

      }

      dc.renderAll();

Any pointers will be appreciated.

**Comment by gordonwoodhull** [comment]
First, crossfilter "dimensions" aren't normal mathematical dimensions, they are the values you want to reduce. The reduced values will map to y. So you probably won't need the y axes below.

Next, if there's one y value per x value, then reducing by sum should be the same as not reducing. (There are other ways to supply data without using crossfilter, but they are more tricky/complicated.)

Corrections/comments inline --

> On May 11, 2016, at 5:39 PM, Rohit garg <notifications@github.com> wrote:
> 
> Hello ,
> 
> I have computed data which doesn't require map reduce operations. I am just trying to make a line chart using dc.js. I couldn't figure out how to put data on y axis.
> 
> dataset 
> [{y:12,x=1},{y:20,x=2},......]
> 
> code:- 
> var ndx = crossfilter(dataSet);
> 
>     //define dimensions
>     var xaxis = ndx.dimension(function(d) {
>       return d.x;
>     });
> 
>     var top = xaxis.top(1)[0].x;
>     var bottom = xaxis.bottom(1)[0].x;
This won't work because these are the top and bottom by reduced value (y). Instead:

var extent = d3.extent(dataSet, function(d) { return d.x; });
var bottom = extent[0], top = extent[1];
> 
>     //Metrices
>     var yaxis = ndx.dimension(function(d) {
>       return d.y;
>     });
Not needed.
> 
> 
>     var exp = xaxis.group().reduce(function(d){
>         console.log(d);
>     });

var group = xaxis.group().reduceSum(function(d) { return d.y; });
> 
>     chart
>     .width(600)
>       .height(220)
>       .margins({
>         top: 10,
>         right: 50,
>         bottom: 30,
>         left: 50
>       })
>       .dimension(xaxis)
>       .group(yaxis)
.group(group)

**Comment by rohit-guitar** [comment]
@gordonwoodhull :- Thanks for the pointers, it works. I need to understand more about crossfilter.

**Comment by gordonwoodhull** [comment]
Great! Glad to have this documented somewhere.
