### ISSUE TITLE
no ordinalColors function found

### ISSUE THREAD

**Issue by jlean1975** [dc-js/dc.js#1143]
I have been using the dc.min.js file from Github recently as a saved file on my local machine. As part of the move to deploy the project I amended my index.html file to reference the cloudflare hosted version. When I did this I found that the dc.min.js remote version did not recognise the ordinalColors function. Is it possible that the remote version needs to be updated or fixed?

**Comment by gordonwoodhull** [comment]
Try getting your links from here:

https://cdnjs.com/libraries/dc/2.0.0-beta.29

2.0 has been in beta for a very, very long time, but it will be released soon. Probably you landed on 1.7.5 because that is technically the stable version, but if you've been using the github.io version, that's the 2.0 beta, and if you've been using the github.com version, that's the develop 2.1 branch.

More info in this thread:

https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/dc-js-user-group/9cDvHFKdR1E/FYyCUuIcBAAJ
