### ISSUE TITLE
Pie chart external label not showing.

### ISSUE THREAD

**Issue by davidhan527** [dc-js/dc.js#1148]
![image](https://cloud.githubusercontent.com/assets/4370987/15597230/2709a7bc-239c-11e6-94d3-ffc224c6db47.png)

version:  dc 2.0.0-beta.26

No matter how much I change the the numbers of the different values, or change the ordering that the functions are called, the top portions of the external labels are not showing. I'm mainly following the example provided here: http://dc-js.github.io/dc.js/examples/pie-external-labels.html

Any idea why this is happening?

```
    stageStatusChart
      .width(300)
      .height(300)
      .radius(130)
      .dimension(stageStatus)
      .group(stageStatusGroup)
      .drawPaths(true)
      .externalRadiusPadding(50)
      .externalLabels(40);

    applicationStatusChart
      .width(300)
      .height(300)
      .radius(130)
      .externalLabels(40)
      .externalRadiusPadding(50)
      .ordering(function(d) { return d.key; })
      .drawPaths(true)
      .dimension(applicationStatus)
      .group(applicationStatusGroup);
```

**Comment by XaserAcheron** [comment]
Have you tried setting `minAngleForLabel` to zero? It may be (somewhat unintuitively) preventing the labels from being drawn on the smaller slices.

**Comment by gordonwoodhull** [comment]
Whoah. My first thought was "now there's an anti-feature!" But I guess `minAngleForLabel` was designed for when the labels are drawn inside the pie, and we added the external labels later.

Thanks @XaserAcheron! Maybe we should disable this feature when external labels are enabled.

**Comment by davidhan527** [comment]
@XaserAcheron that worked! thank you!

**Comment by XaserAcheron** [comment]
Cool! Glad to help! :)

Yeah, the current behavior is a bit odd, but rather than disabling it entirely, here's an alternative proposal:

- Use a default of zero for `minAngleForLabel` if external labels are used.
- Hide the lines as well as the labels when `minAngleForLabel` is specified, so you get something like this instead:

![delicious pie](http://i.imgur.com/hWm4oM0.png)

This way the default behavior is less confusing and there's a good use for the feature with external labels. I imagine the labeling can still super-crowded if the slices get sufficiently small.

I might PR this if I get some free time, just for funsies.
