### ISSUE TITLE
Missing values on zoom reset

### ISSUE THREAD

**Issue by altcomGaillard** [dc-js/dc.js#1179]
I'm working on a scatter plot.
I set my chart as mouseZoomable(true).

I've created an action to reset the zoom to go back to the original view.
It all works fine apart from the fact that the points which were previously out of the visible domain don't reappear.

To run the zoom reset I set the (time) domain in x back to the original values then I run a renderAll.
`$scope.chart.x(d3.time.scale().domain([$scope.minDate, $scope.maxDate]));
dc.renderAll();`

**Comment by gordonwoodhull** [comment]
I'm not able to repro this either, again modifying the scatter brushing example as I mentioned in #1178. I believe you, but I'm going to need more information or a running example to troubleshoot this.

**Comment by altcomGaillard** [comment]
I've created a fiddle which shows both #1178 and #1179 bugs.
http://jsfiddle.net/altcom_gaillard/djchar8o/2/

For some reasons, the behaviour has changed since I've reported the bug. Not sure why...
Instead of completely disappearing, the values appear differently. The cause is probably the same though.

**Comment by gordonwoodhull** [comment]
Thanks for the example! I had to update crossfilter.js to run this, for some reason.

http://jsfiddle.net/gordonwoodhull/Lb9vmj29/2/

Looks like it's actually assigning the scale that disables zoom.

**Comment by gordonwoodhull** [comment]
For better or worse, dc.js filters coordinate grid charts to the current zoom. This may not be wanted in all cases, and maybe it's worth thinking about an option. 

Since you're explicitly setting the domain (and dc.js won't know about it), you can reset the filters one of two ways, explicitly:

```js
    $scope.chart.x().domain([$scope.minDepth, $scope.maxDepth]);
    $scope.chart.filter(null);
```

.. or by calling the same method that the range chart uses when it resets its focus chart:

```js
    $scope.chart.focus(null);
```
http://jsfiddle.net/gordonwoodhull/Lb9vmj29/8/

If you're interested in not filtering on zoom at all, please open another issue.

**Comment by altcomGaillard** [comment]
Thanks! That's working with "filter(null);" for me.
