### ISSUE TITLE
force-directed bubbles

### ISSUE THREAD

**Issue by FabianColque** [dc-js/dc.js#1236]
Hi all,
I only want to know if it is possible to do a bubble chart 
like https://bl.ocks.org/mbostock/4063269, because i dont want to have the
axes in my chart.
Please help me, how i might to do.

**Comment by gordonwoodhull** [comment]
That's an entirely different kind of bubble chart from the one in dc.js core - it uses a force directed layout to place the bubbles, rather than using the data itself.

There is one of these available in Ruhley's dc-addons:
https://libraries.io/bower/dc-addons#bubble-cloud

Haven't tried it myself.

Cheers 
Gordon

**Comment by gordonwoodhull** [comment]
I'm going to close this since the chart exists in the larger ecosystem. Feel free to ask [on StackOverflow](http://stackoverflow.com/questions/tagged/dc.js) or on the [user group](https://groups.google.com/forum/?fromgroups#!forum/dc-js-user-group) if you have further questions.
