### ISSUE TITLE
Is there scrolling function along with x axis.

### ISSUE THREAD

**Issue by yumere** [dc-js/dc.js#1243]
If I have range of 0-1000 data, I want to show data just ranged 0-500 on the screen.

And then when I scroll right, show 500 ~ 1000.

But If I set x axis `.x(d3.scale.linear().domain([0, data.length])`, 

These code show entire x axis. And I use only `mouseZoomable`.

I don't want to use `mouseZoomable` function because of overhead if I have large data(about 100,000).

**Comment by gordonwoodhull** [comment]
`mouseZoomable` is the way to do panning/scrolling. Is it really so slow?

Maybe you need to aggregate your data better. If each item shows as its own SVG element that is going to bog the browser down. But there aren't that many pixels in either axis, either. 

The idea of crossfilter is to aggregate in order to bring the data down to a reasonable size so that it can be displayed. (Doing calculations on that much data is usually not a problem, just displaying it in the DOM.)

**Comment by gordonwoodhull** [comment]
I'm going to close this because IMO `mouseZoomable` should be sufficient. I'm not surprised if there are bugs in this feature, but I don't think we need another feature for this.
