### ISSUE TITLE
When click on bar while bar transition is in progress, all bars disappeared

### ISSUE THREAD

**Issue by AshwiniAJadhav** [dc-js/dc.js#1285]
When click on bar when bar transition is in progress, all bars disappeared
We are using bar charts in our project. When user clicks on one bar, only clicked bar is displayed and rest all bar get disappeared. When user again clicks on same bar, all the bars get displayed(reset to original). TransitionDuration for bar chart is default .  Issue which I am getting is when I am clicking on bar when transition of bars is in progress, all bars get disappeared.(This occurs on second click)
![image](https://cloud.githubusercontent.com/assets/26269956/23695569/e091e7cc-0405-11e7-8984-2f3a5ccb108a.png)
![image](https://cloud.githubusercontent.com/assets/26269956/23695598/0ba35856-0406-11e7-8ea5-66963f203f70.png)
![image](https://cloud.githubusercontent.com/assets/26269956/23695624/2de10242-0406-11e7-8e4c-767f3e9c3432.png)
![image](https://cloud.githubusercontent.com/assets/26269956/23695637/3d8485e8-0406-11e7-9f47-b74136070e54.png)

**Comment by gordonwoodhull** [comment]
Hmm, I don't think I've seen this before. Can you create a fiddle or other reproducible example?

The fact that bars are disappearing when the chart is clicked, as in the second image above, suggests that perhaps the chart's group is not based on its dimension. Usually you want those to match [so that the chart does not filter itself](https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#a-group-does-not-observe-its-dimensions-filters).

**Comment by gordonwoodhull** [comment]
I'm going to guess this was a group/dimension mismatch - please comment if this is still an issue for you.
