### ISSUE TITLE
Tests are broken on develop

### ISSUE THREAD

**Issue by mtraynham** [dc-js/dc.js#1294]
https://travis-ci.org/dc-js/dc.js/builds/216810258

Looks like the cap mixin change affected the ordering of results.  Is that intentional?  Was going to rebase a branch or two, but noticed it was broken.

**Comment by gordonwoodhull** [comment]
Yes, the change is intentional, sorry I have not fixed the tests yet. This change is not part of any release yet.

When we eliminated `group.top()`, this changed the ordering of many of the charts. In a few cases, the ordering was broken already (because the group order and `chart.ordering()` didn't agree), so it didn't matter. 

But in most cases, we can emulate the old `group.top()` ordering by sorting reverse by value. That's usually what people want for row charts, and what this change enables.

I'd suggest rebasing against the stable branch (`support/2.0`, currently 2.0.2). Or if you feel like fixing the tests, that's welcome too!

**Comment by mtraynham** [comment]
I'll provide a fix as long as the changes were intentional 😄

**Comment by gordonwoodhull** [comment]
That would be awesome, a second pair of eyes on the tests is always helpful.

**Comment by mtraynham** [comment]
Closing per #1295.

**Comment by gordonwoodhull** [comment]
Thanks!
