### ISSUE TITLE
Error with Bar Charts

### ISSUE THREAD

**Issue by Ohjay44** [dc-js/dc.js#1296]
Im running the dc cloudflare cdn version 2.1.4 and when I try to render bar charts I get an error that `b.size()` is not a function.
Its happening on `var last = layers.size() - 1; ` I saw that someone else had this issue but they were using meteor. Can anyone help me with this?

**Comment by gordonwoodhull** [comment]
So, you found issue #1118 already and it looks like that issue arose because meteor packaged an obsolete version of d3.js.

Could you be facing the same issue? dc.js is compatible with d3.js 3.x but I wouldn't try it with anything less than 3.5.

Ah, I see you closed this while I was typing. Was this the correct diagnosis?

**Comment by Ohjay44** [comment]
Exactly. It was the exact same issue. I miss read the original solution. I thought he said he was using DCjs 3.x and I was confused but it was D3js 3.x. Once I switched it to 3.5 it worked.

**Comment by gordonwoodhull** [comment]
Great, thanks for confirming!
