### ISSUE TITLE
Row chart default view sorted and not reorder while onclick

### ISSUE THREAD

**Issue by caravinden** [dc-js/dc.js#1307]
Hi All 
I have a situation where displaying two-row chart side by side. I need to achieve sorting both the graph with group highest value, this I can achieve through chart.order(). 
Scenario:-
1. The initial load of the chart with sorted values.
2. on Click of the chart, Don't need the sorting or reordering of the bar.  Filter can apply the chart without reordering the bar position

Is there any solution available?

**Comment by gordonwoodhull** [comment]
I'm going to close this in favor of the question on SO. That's really the right place for this sort of question, since this isn't a big report or a feature request.

https://stackoverflow.com/q/44305829/676195

I think it can be done (yep) with a fake group. Hope to get a chance to look at this in the next few days. Thanks for including a fiddle on SO!
