### ISSUE TITLE
Support crossfilter2 v1.4

### ISSUE THREAD

**Issue by guilhermecgs** [dc-js/dc.js#1320]
How difficult would it be to upgrade crossfilter2 to version v1.4?

[V1.4 is a minor update ](https://github.com/crossfilter/crossfilter/releases)

**Comment by gordonwoodhull** [comment]
You can already use the latest dc.js with crossfilter2 1.4 - there are no compatibility problems.

I haven't updated the dependency in package.json because I was hoping to look into the slightly worse performance of crossfilter2 1.4. But this is not a serious issue and I should probably go ahead and update that dependency.

**Comment by guilhermecgs** [comment]
I need to buy you a beer for the 10 min answer service level. :-)

**Comment by gordonwoodhull** [comment]
Yum! Cheers!🍺

**Comment by Ardibee** [comment]
It would be great to get the dependency updated to 1.4 in bower.json too, as Crossfilter2 v1.4 fixes an issue with arrays that I'm using a workaround for.  So +1 for this issue from me :-)  Thanks.
(See https://bl.ocks.org/emiguevara/4bd152a8828f6b31270702d97dc0133d and associated SO threads for the workaround.)

**Comment by gordonwoodhull** [comment]
Dependency updated to `~1.4` in both `package.json` and `bower.json` for release 2.1.10.
