### ISSUE TITLE
barchart cannot select last day

### ISSUE THREAD

**Issue by Smmw** [dc-js/dc.js#1339]
I select all from barchart, I have 19 records, but the table and the Count say there are only 17 records selected.

```js
                                 totalAmountPerDayBarChart
					.width(1200)
					.height(300)
					.margins({top: 10, right: 50, bottom: 30, left: 40})
					.dimension(dateDim)
					.group(totalAmountPerDayGroup)
					.elasticY(true)
					.centerBar(true)
					.gap(0)
					.outerPadding(100)
					.round(d3.time.day.round)
					.alwaysUseRounding(true)
					.x(d3.time.scale().domain([minDate, maxDate]))
					.renderHorizontalGridLines(true)
					.xUnits(d3.time.days)				
					.filterPrinter(function (filters) {
						var date1 = filters[0][0];
						var date2 = filters[0][1];
						// date2.setDate(date2.getDate() - 1);
						return date1.getFullYear() + '/' + (date1.getMonth() + 1) + '/' + date1.getDate() + 
							' - ' + date2.getFullYear() + '/' + (date2.getMonth() + 1) + '/' + date2.getDate();
					});
```

**Comment by gordonwoodhull** [comment]
Why did you remove the screenshot and text? I put the text back in.

I'm going to guess you have data on April 5 and you are running into #792. Even though you are computing the domain manually, dc.js interprets the domain too literally and won't show the last bar, because it simply shows exactly the domain, and the last bar starts on the end date.

Workaround is to increment the upper bound of the domain by one unit, as shown in that issue.

**Comment by Smmw** [comment]
Yes, I added 1 second for the max date, then disable the alwaysUseRounding and round.
It works now. thanks!
