### ISSUE TITLE
dc.errors.InvalidStateException

### ISSUE THREAD

**Issue by Smmw** [dc-js/dc.js#1352]
When I put the this variable globally 
var groupsRowChart = dc.rowChart("#groupRowChart");
It will throw me this error. It was working on my last project. This time did not working.
![image](https://user-images.githubusercontent.com/3632980/32761473-5e1cef44-c958-11e7-8f9b-c12b4b43e9b9.png)

**Comment by gordonwoodhull** [comment]
You've probably changed the order of initialization.

The error means that you need to initialize `dimension` before rendering the chart.

If you think this is incorrect, you'll need to supply an example. The error is there because the chart needs this data to draw anything. If it weren't there, the failures would be a lot harder to understand. As such, it should be self explanatory.
