### ISSUE TITLE
Does it work with Vue.js?

### ISSUE THREAD

**Issue by hifall** [dc-js/dc.js#1442]
This project looks really impressive!

Has anyone used this inside a Vue.js-based project? Does it get along with Vue?

Thanks!

**Comment by gordonwoodhull** [comment]
I don't see why there would be any problem. It doesn't use any of the Vue paradigms, but Vue is designed to be incrementally adoptable.

I haven't used Vue and I have only used Angular a little bit. I've seen two approaches used for including dc.js charts in Angular projects; I think Vue would be similar. 

One is just to implement all the dc.js charts in the controller, as "plain JavaScript".

The other is to define Angular directives, like [angular-dc](https://github.com/TomNeyland/angular-dc) does for Angular 1. This is more idiomatic but it requires some maintenance of the directives.

I'm sure one could define Vue components to wrap dc.js charts. I guess it's worth it if you want to use pseudo-HTML to define your charts instead of JavaScript.

I'll leave this open for a week or two in case anyone has specific experience they'd like to share. But I don't think there is any action required in the library to support this.

**Comment by MorayM** [comment]
Yes, I'm using it with Vue.js with no problems. I've done it by putting the code to draw the charts into a method on my component which gets called on `mounted()`, and I've put a watch on the prop containing the source data so that the charts are redrawn if the data changes.

**Comment by grugknuckle** [comment]
I am currently developing a huge enterprise app with Vue.js 2.x and I use dc.js extensively within it. Yes it works.

**Comment by gordonwoodhull** [comment]
Thanks @MorayM, @gregknuckle!
