### ISSUE TITLE
search filter not working for aggregate table

### ISSUE THREAD

**Issue by jay2452** [dc-js/dc.js#1502]
I am trying to implement data table with aggregation along with text based search filter. 
But the filter by text is not working where as for non aggregated data the text filter is working fine.

example: (https://jsfiddle.net/nm0k5dvf/1/)

**Comment by gordonwoodhull** [comment]
Hi @jay2452, there is an interesting special case in crossfilter where [a group does not observe its dimension's filters](https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#a-group-does-not-ways observe-its-dimensions-filters).

So typically if you want one chart or widget to affect another, they need to be on different dimensions. The reason it w
orks without aggregation is that there is yet another special case where `dimension.top()` *does* observe that dimension's filters. I think that's because `dimension.top()` is often used for tables, and tables can't filter anything else. (Just a guess.)

If you create another dimension with the same definition, and use it for the text filter widget, it does filter the table:

```js
var custDim2 = dataCrossfilter.dimension(d => d.name);
searchBox.dimension(custDim2);
```

[Fork of your fiddle](https://jsfiddle.net/gordonwoodhull/512bvkqo/2/).

You could further use [`remove_empty_bins()`](https://github.com/dc-js/dc.js/wiki/FAQ#remove-empty-bins) if you want the rows to disappear rather than the totals just going to zero.
