### ISSUE TITLE
dataCount problem with VueJS

### ISSUE THREAD

**Issue by JWDobken** [dc-js/dc.js#1518]
While working with dc.js in VueJS I ran into the problem that the dataCount does not work properly. The dataCount component is not rendered and when making a selection in any other chart it gives the following error:

> TypeError: a.dimension(...).size is not a function

It's demonstrated with this [jsfiddle](https://jsfiddle.net/jwdobken/m98x7j1b/39/): which is loosely based on the [tutorialsPoint](https://www.tutorialspoint.com/dcjs/dcjs_data_count.htm) example. About the structure: I tried to include a more VueJS-ish approach with methods and use the mount as suggested here #1442.

**Comment by gordonwoodhull** [comment]
Related: #1499

**Comment by gordonwoodhull** [comment]
Hi @JWDobken!

There are a couple of problems here:
1. As mentioned in the above linked issue, `dataCount.dimension()` (and arguably `dataCount.group()`) is shamefully misnamed. I have no idea why someone thought it was a good idea to reuse method names for different purposes, but here `.dimension()` should be passed the crossfilter object itself, and `.group()` should be passed a groupAll object - usually one returned from `crossfilter.groupAll()` because you are interested in the number of rows filtered overall, not [excluding one of the dimensions](https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_groupAll).
2. You had an extra div in there with the *class* `id-data-count`. I am embarrassed how long I struggled with this simple problem.

[Working fork of your fiddle](https://jsfiddle.net/gordonwoodhull/3uky6fnL/15/).

As I've updated #1499 with a plan forward, I'm closing this as a dupe. Feel free to comment if you have further questions!

**Comment by JWDobken** [comment]
Thanks for the comprehensive answer! I am sorry you also had to solve the second problem

**Comment by gordonwoodhull** [comment]
No problem! It's weird how it takes more effort to fix the obvious things than the subtle things, sometimes.

Yes, these misnamed methods are super frustrating for new users. Now that we have a backward compatible plan to fix them, I  hope we can put them in the past.
