### ISSUE TITLE
SunBurst and CapMixin

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1573]
Currently SunBurst mixes in CapMixin. I am unsure if it can actually support capping in a logical and meaningful way.

@gordonwoodhull need your advice.

**Comment by kum-deepak** [comment]
Removing CapMixin from SunBurst is not complicated and test cases still pass. I will make it as a commit into charts. We will drop it if needed.

**Comment by gordonwoodhull** [comment]
I am not sure how useful it is, but it works almost as I would expect - it limits the number of top-level slices.

It has a bug where it splits the title "Others" across 6 cells:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1366709/64738660-ce815280-d4bd-11e9-9385-85d4fc7e1227.png">

I would expect just the innermost indigo slice to be titled Others, with no children. This bug isn't surprising because capped charts always need a lot of special cases to deal with the extra item.

I don't remember anyone complaining about it, so I don't think the feature is getting much use. I think it's mostly there because the author based the sunburst chart on the pie chart. 

I agree, it's safe to remove it, and we can revert it later if needed.

**Comment by kum-deepak** [comment]
Thanks! I have made a commit. I will close this issue.
