### ISSUE TITLE
clickable bar charts not clickable if not dc.units.ordinal

### ISSUE THREAD

**Issue by jrhite** [dc-js/dc.js#168]
To make a bar in a bar chart clickable the xUnits on the bar chart needs to be of type dc.units.ordinal.

I have a bar chart which uses xUnits(d3.time.days). It's 'ordinal' but not dc.units.ordinal. I'd really like to make this chart clickable, but the current implementation doesn't allow me to.

**Comment by gordonwoodhull** [comment]
So, it appears that the reason `.on("click", _chart.onClick)` does not work is that when 8b3c6ff854e1cd7e3d2760faaea78aae1c194e82 restored `onClick` behavior for ordinal charts, `onClick` became a private function rather than an override of the base function.  

(And using the base's `onClick` does not work because the data is wrapped by the stack algorithm in e6512202fdcc77b4c0b7373323308f499d610f57, which incidentally also removed the click behavior for ordinal bar charts.)

I am fixing this in 2.0.0-beta.4

**Comment by anmolkoul** [comment]
Hey @gordonwoodhull , 
If i have a stacked bar chart, Is it possible to drill down on the rest of the data (charts) by clicking on a segment (stack) of the stacked bar chart? Right now the whole ordinal category gets selected on click.

Much thanks.

**Comment by gordonwoodhull** [comment]
Hi @anmolkoul, that would be request #657. I think you can do it by adding a custom click event, but I haven't tried it myself.
