### ISSUE TITLE
Explore Mixins - again

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1703]
Investigate if we can do Mixins in a more Typescript friendly way. 

Initial lead: https://www.stevefenton.co.uk/2017/08/typescript-mixins-part-two/

**Comment by kum-deepak** [comment]
The previous way of Mixins worked well for ES6. However, it was not enough for Typescript. 

- We need proper type checking in Mixins themselves - the compiler needs to figure out the methods a Mixin is using from possible Bases.
- We need proper type checking in derived classes, the compiler needs to figure out all combined methods.

There is some issue around generating declaration for anonymous classes. There are known workarounds based on https://www.typescriptlang.org/docs/handbook/mixins.html. One such workaround is at https://github.com/microsoft/TypeScript/issues/17744#issuecomment-468748859

After refactoring, we may have fewer Mixins. At that stage, the workaround would be implemented.

**Comment by gordonwoodhull** [comment]
I took a look at these `defineProperty` loops. I guess it's a form of metaprogramming, generating the class by running a program.

It's too bad that it does not use language constructs, but I guess it's fairly clear what is going on. In a way it is a step back toward dc@3 in that it builds the classes dynamically instead of using classes and inheritance. 😉

**Comment by kum-deepak** [comment]
Yes, it feels really sad having to go back.

Our usage is quite specific. So, I guess that we can try some simpler approaches as well. I will get back to it after a few rounds of refactoring.
