### ISSUE TITLE
Regarding issue in dc bar chart ordinal scale brush selection

### ISSUE THREAD

**Issue by shijocj** [dc-js/dc.js#1770]
I am using dc version 3.0.2, d3 version 5.15.0 and crossfilter version 1.3.12 .I have multiple row charts and one bar chart, and my bar chart has ordinal values and need to implement brush selection(range filter) on bar chart.

When I go through the dc.js documentation I found that ordinal scale won't support brush selection. So I followed [the brush ordinal example](https://dc-js.github.io/dc.js/examples/brush-ordinal.html ), and I implemented the same logic. When it comes to interaction in charts, if I select any item in bar chart using brush selection, it's working as intended and reflecting in row charts. However, when I click any item in row charts, it's not reflected in the bar chart - filtering is not happening in the bar chart. 

I guess the brush ordinal example I mentioned above is also not working correctly, because if I click any of the item in row chart , bar chart displaying negative values in Y axis. I think the result is wrong.

**Comment by gordonwoodhull** [comment]
There were two problems in the example:

1. `sort_group` was calling `group.all().sort()`, which you should not do, because [group.all() returns a reference to an internal array](https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#groupall-returns-a-direct-reference-to-the-internal-group-array). If you copy the array using [.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice), then it is safe.
2. Coordinate grid charts currently need to be told when the the X domain changes, by calling `.rescale()`. Since this was not called, the tick labels did not update on the bar chart when filtered.

I've fixed the example in version 4.1.1.
