### ISSUE TITLE
Serialize / deserialize filter status

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1778]
Ability to do so at the chart and chart group level. This will allow saving / restoring state (in terms of filters) for the entire chart group. Can be used as undo/redo, or to even save in secondary storage across user sessions.

One challeneg remains - how do we identify charts (or dimenions) across sessions. One approach can be chart anchors. @gordonwoodhull any ideas?

**Comment by gordonwoodhull** [comment]
Agree, if we are composing an object of all filters, `.anchorName()` would be a good choice: it is guaranteed to be a unique identifier for the chart.

It is not sufficiently documented, but it checks if the anchor is an element, if so uses its id; if it's a string selector it removes `#`; otherwise it creates a string based on the chart's unique integer id. 

Therefore it will work in all cases, and work optimally in the most common case, where unique `#id` selectors are used.

I suppose if we wanted we could have another level of customization over that, but it's a great default.

**Comment by kum-deepak** [comment]
Thanks, Gordon! That is helpful. Initial changes are same as needed for #1777. I will make a merge than diverege.

**Comment by kum-deepak** [comment]
Implemented in #1795
