### ISSUE TITLE
How to change x ticks wording programmatically

### ISSUE THREAD

**Issue by ewaldman** [dc-js/dc.js#1782]
Hi.
I have a LineChart to display dates with months. For instance Nov. Or, Oct. etc.
It works fine. One problem is: when it displays months the ticks have the long month name (November  , October , etc). This happens when we have data spanning across a few months, the chart prints the long month name at the point the months change.
We would like it to say the short month names (Nov, Oct).  We tried doing it programmatically but it didn't work.
What can we do to specify upon chart creation that it should use short month name (Nov, etc).?
Or, what can we do to change it programmatically?

Here's what we tried:

```
lineChart.selectAll('.x.axis text').each(function(d, index, nodeList) {
         
          const el = d3.select(nodeList[index]);
          el.text(".....");  //  here is where we format what I want.       
          
        });
```

**Comment by gordonwoodhull** [comment]
That would be

```js
chart.xAxis().tickFormat(d => /* format d.key here */)
```

See the [d3-axis documentation](https://github.com/d3/d3-axis/tree/v2.0.0) for more details, and be sure to do this in a separate statement since [this starts a chain on the axis object, not the chart](https://github.com/dc-js/dc.js/wiki/FAQ#why-does-everything-break-after-a-call-to-xaxis-or-yaxis).

**Comment by ewaldman** [comment]
Thank you
