### ISSUE TITLE
 geoChoroplethChart India chart 

### ISSUE THREAD

**Issue by satra2806** [dc-js/dc.js#1844]
@gordonwoodhull  , is there any any example code for India  geoChoroplethChart

**Comment by gordonwoodhull** [comment]
Hmm, I think I have seen this in the past, but I looked on the wiki and stack overflow and didn't see one.

My understanding is that the tricky part is to set the projection correctly. You may be able to find straight D3 examples and then work backward from there, since dc.js is built on top of D3.

Sorry I don't know any more!
