### ISSUE TITLE
Feature Request: Labels above bars in bar chart

### ISSUE THREAD

**Issue by wolframarnold** [dc-js/dc.js#211]
Hi Nick, Weidong,

I know that the label method isn't effective for bar charts, but I'd like to make a feature request to add labels above the bars in a bar chart. It would be really helpful to see, e.g. the total bar height as a label above the bar. Similar as the labels in the row chart or the pie chart, but above the bar.

I love your work. It's been very helpful.

Cheers,
Wolf

**Comment by nreese** [comment]
What is the status of this issue? Did a pull request ever get merged into the baseline? If so, is there an example showing how to create a bar chart with labels?

**Comment by gordonwoodhull** [comment]
Hi @nreese there's never been a PR on this. I'd go with @dimirc's second answer to the SO question above, and take @mr23's answer into account as well. If you want to file a PR that would be awesome.

**Comment by nreese** [comment]
How should labels behave for stacked bar charts?

**Comment by gordonwoodhull** [comment]
I think they would just show the total. It would be kinda messy to have them overlay the next bar up...

**Comment by nreese** [comment]
I was thinking of placing the labels above the bars. What should happen if there is not enough space between the top of the bar and the top of the chart for the label? Should the label be placed below the bar top for these instances?

**Comment by gordonwoodhull** [comment]
I would expect the domain of the chart to stretch a bit in that case. But I guess it's debatable.

**Comment by nreese** [comment]
It looks like the domain can be expanded by setting yAxisPadding. Should dc.js try to automatically set yAxisPadding to an appropriate value when rendering labels or should this be left up to the developer to manually set yAxisPadding as they see fit?

**Comment by gordonwoodhull** [comment]
Sure. It's not perfect because it will also expand the padding below the chart, but it will do.

I would just leave it to the user, since we do not even automatically adjust the margins for axes or axis labels. (It would be nice, but probably better to address the layout problem in a comprehensive way. Like the others, this one depends on text height, which is somewhat tricky.)

**Comment by nitinsurana** [comment]
+1 for having labels for stacked bar charts too. It'll be nice to have configurable option to decide the placement position in the bar - top/bottom/center.

**Comment by prashant22april** [comment]
Hi All,
I urgently require a error bar charts using dc.js. Any help in this area would be highly appreciated. Something similar to the below image I am looking out for:
![download](https://cloud.githubusercontent.com/assets/15922042/17547940/20b2a07a-5f07-11e6-8a8d-dce332b8fa79.jpg)

**Comment by gordonwoodhull** [comment]
Hi @prashant22april, this is an interesting request. However, it's unrelated to this issue (although slightly similar). And I just noticed this issue is actually closed (implemented in #1031 for 2.0 beta 21). 

Please open a separate issue, or better yet, create a jsfiddle or bl.ock with some sample data and post the question on SO, and I'll try to implement a renderlet solution (without having to change dc.js).

@nitinsurana, I just noticed your comment here. That's also a separate request from this ticket, which is closed. Could you please open another ticket with the options you'd like to see?
