### ISSUE TITLE
Alternative Data Table

### ISSUE THREAD

**Issue by jrideout** [dc-js/dc.js#227]
I needed a data table that showed aggregated data from group-reduce, rather than one extracted from the underlying records and grouped. Here is a gist showing my version:

https://gist.github.com/jrideout/6080902

There are a few things I don't like, so I didn't submit a patch. Hopefully we can integrate my intent here with the core data-table class to create a new version with more features.

Changes:
- Ignores dimension and sortby
- Columns are based on the group, grouping rows no longer occurs by necesity
- Columns are kept, based on a `keep` callback that along with size limits returned rows. This allows for keeping all records with some computed value > 0 for example.

**Comment by gordonwoodhull** [comment]
For the past five years people have been passing a group as the dimension, which looks equivalent to this.

We’ve had [an example]( http://dc-js.github.io/dc.js/examples/table-on-aggregated-data.html ) since 2015, and sometimes it requires workarounds like implementing `.bottom` for ascending order, but it basically works.

Not elegant, but neither is having a second table implementation, so I think we can close this.
