### ISSUE TITLE
dataTable - filter by selecting a row?

### ISSUE THREAD

**Issue by jbwl** [dc-js/dc.js#534]
I am using the seriesChart in combination with a dataTable, and I would like to be able to filter the seriesChart by clicking on a row of the dataTable. I can't find an "onClick" event in dataTable so I guess it's not possible?

My use case is display a table of country names and series of sales data for each country. I would like to be able to click on a country in the table and toggle off all the other countries (=series) in the seriesChart. Optimally the seriesChart should be redrawn to optimally display the one series.

**Comment by renoth** [comment]
This seems to be an issue in 2.0.0-beta10,
when doing
```
datatable.onClick(function(d) {console.log(d);});
```
i get 
```
TypeError: filter is undefined
http://localhost:8080/myapp/dc/dc.js      Line 725
```

**Comment by cmorgan** [comment]
same issue with dc.js 2.1.8

**Comment by gordonwoodhull** [comment]
1. @renoth and everyone else who has tried 

```js
datatable.onClick(function(d) { ... });
```

No fault of yours, but that's the wrong way to use `onClick`. I apologize for my uninformed advice years ago, but that's not a standard customization point for dc.js, and you'd have to actually **assign to it** for it to work.Yes, that's evil and wrong. Lots of people have worked on dc.js over the years, and this was a mistake by someone who didn't understand the API.

2. It doesn't work anyway, because the data table does not register a click handler.

So... go with the standard way. Once the chart is rendered, in a renderlet or pretransition event listener, create your own click handler, and namespace it so that it doesn't clash with any others:

```js
my_table.on('pretransition', function (table) {
     table.selectAll('td.dc-table-column')
          .on('click.my-event',function(d){
                console.log(d);
           })
});
```

Then you'll need to apply the filter yourself. It matters whether you are displaying a dimension or a group in your data table.

Here's a recent (and better-informed) Q&A on the topic, with details on both of the possibilities:

https://stackoverflow.com/questions/44957203/click-in-datatable-to-filter-other-charts-dc-js

Let's flush out the misinformation! @cmorgan, if you still can't get this to work, please either ask a question on SO, or reply here, and we'll get it right this time!

**Comment by conor909** [comment]
Does anyone know how to target an individual cell?  I tried added a custom format into certain columns and adding a class.  Then targeting the class, but in that case `d` is undefined.

```
table
   .columns([
        'date',
        'open',
        'close',
        {
            label: 'My Header',
            format: function (d) {
                return "<a class='clickable-item'>" + numberFormat(d.close - d.open) + '</a>';
            }
        }
...
.on('renderlet', function (table) {
            table.selectAll('td.dc-table-column .clickable-item')
                .on('click', function(d) {
                    routerHistory.push('/', { object: d }) // d is undefined
                })
        });
```
