### ISSUE TITLE
DC extents, high side non-inclusive?

### ISSUE THREAD

**Issue by mr23** [dc-js/dc.js#568]
Can someone comment on why the high end of ranges is non-inclusive while the low side is inclusive?

I'm seeing on area selections in the scatterplot the highest point(s) are not included. If I change the extent code to use <= instead of < then it functions as expected.

dc.filters.RangedFilter
     return value >= this[0] && value < this[1]
dc.filters.RangedTwoDimensionalFilter
_chart.fadeDeselectedArea
and possibly other locations.

I expect this is because it is using the same basic filter code as for Dimensions, which by nature you do not want to double include points at boundaries between/into groups. However, the charting selection needs to be inclusive.

I might get around to fixing this, but not this weekend.

**Comment by TheStoof** [comment]
You can work around this by adding +1 to your range, if possible; I'm here because I ran into this problem as well, but instead of patching, I went with modifying the range outside the bounds of the known data by calculating the range and adding '+1' to the max.

**Comment by gordonwoodhull** [comment]
As noted in #1066, `.xAxisPadding("0.001%")` will make the last point selectable if you're using `.elasticX(true)`, and this will work with any magnitude.

Per #478, `RangedFilter` is usually "optimized out" to use [dimension.filterRange](https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_filterRange) instead, and that uses inclusive lower bound, exclusive upper bound. It's a very computer-sciencey way to go about things, but given that crossfilter is more of a UI library than a computational library, it's arguable that it should do what you expect rather than what's nice mathematically.

**Comment by gordonwoodhull** [comment]
Given this is the way crossfilter works and there are decent workarounds, I'm closing this. Like it or now, crossfilter defines the standard framework and worldview for dc.js.

I think #792 including the rightmost bar, would also fix this, and that's a more glaring problem.
