### ISSUE TITLE
Line Chart's interpretation of null values

### ISSUE THREAD

**Issue by bgeels** [dc-js/dc.js#615]
Currently in the lineChart widget it is the default behavior to ignore null values and just connect the two closest data points resulting in a straight line going through the timestamps with null values.

Is there any way to override this behavior so I can say something like if( d.data.value === null) stop drawing this line segment and start a new one?

I included a jsfiddle example here, http://jsfiddle.net/mater_tua/QD9Ev/. The result I would want is two line segments. The first one ending at, 2014-06-09T18:50:00.000Z, and the second starting at, 2014-06-09T21:25:20.000Z.

**Comment by andorov** [comment]
I've added a code example to stackoverflow -

https://stackoverflow.com/questions/24413683/dc-d3-line-chart-crashing-down-to-0-on-the-y-axis-after-filtering/29020499#29020499

**Comment by pianomister** [comment]
I do not know if this was caused by my special setup:
I am rendering a bunch of composite charts with lines using the same configuration but different filters each. The charts are generated by a forEach loop. The function for defined() was only working on the first chart properly, although all charts used a copy of the same config:

```javascript
.defined(function(d) {
    return d.y != null;
})
```

Using a function which is not returning true/false but the actual value (like the crossfilter filter functions), fixed the problem for me:

```javascript
.defined(function(d) {
    if(d.y !== null) {
        return d.y;
    }
})
```

Maybe this helps in case someone has the same problem.
