### ISSUE TITLE
Labels are overlapped by slices in pie chart

### ISSUE THREAD

**Issue by vadimzv** [dc-js/dc.js#664]
Here it can be reproduced http://vzv.ucoz.ru/dc/pietrouble.html
Click on Deposits on the first chart, the second chart will be filtered, then click on Deposits again so the second chart will be reverted to the original state. Upper label (Contract enforcement) in the second chart is now partially hidden by the slice.
This bug happens because slices (g tags in svg) and labels (text tags) are mixed while all slices must come first and after them must come text tags. To fix it you can add

	_g.selectAll("text." + _sliceCssClass).remove();
before

	createElements(slices, arc, pieData);
So all labels will be recreated.

**Comment by maackle** [comment]
Is anybody working on this? I tried to quickly add a fix to put labels in a separate `g`, but saw it wasn't trivial. I might try again, unless there's a solution in the works.

**Comment by gordonwoodhull** [comment]
Hi @maackle, that would be great. You're right, it is slightly more complicated because it means you need to start two separate `select(...).selectAll(...).data(...)` roots. But it shouldn't be too difficult. 

If you find this too difficult, you could always use a `'preRedraw'` event hook to delete any existing text at the beginning of redraw, as a temporary workaround.

https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#basemixinonevent-listener--basemixin

**Comment by maackle** [comment]
@gordonwoodhull I made a PR for this. You're right, it was pretty straightforward (after I remembered how d3 works!). There could be some discussion about CSS class names; I wound up giving classes to the new groups as well as adding an extra class to labels, though none of that was strictly necessary.

**Comment by gordonwoodhull** [comment]
Fixed in 2.0 beta 32. Thanks @maackle, @vadimzv!
