### ISSUE TITLE
Add support for horizontal box plot

### ISSUE THREAD

**Issue by amergin** [dc-js/dc.js#701]
The current box plot implementation is really cool, but could you please support horizontal box plots as well? Currently, I don't see an option to do this, and it would not make much sense to override svg code with `renderlet` to achieve it, without touching the internals.

**Comment by BermudaLamb** [comment]
Is this on the roadmap for implementation? It was added to the v2.1 milestone, but that milestone has been deleted.

**Comment by gordonwoodhull** [comment]
Hi @BermudaLamb, the milestones always had more to do with which changes could be made without breaking the interface, so I changed the names to reflect that. There is an old roadmap in the wiki but I think it has been superceded.

There is obviously no paid staff developing this library, and the direction and pace of development has more to do with
 1. what people are able to contribute as PRs
 2. the quality of those PRs: whether they have tests, whether they break other functionality, etc

I.e. things can get merged fairly quickly when I find time to make a release, if they are ready to go, but things that are not ready take a lot longer because either I have to complete the work or find someone to volunteer to complete it.

It shouldn't be that hard to adapt the box plot code, but it might be tricky to do in a reusable way so that there is not a lot of duplicated code between the two orientations.

I'm going to close this issue because #1310 is a duplicate and has more details on the work required. If you have any interest in contributing, please see that issue and comment there.
