### ISSUE TITLE
rangeChart glitch

### ISSUE THREAD

**Issue by yihaotan2012** [dc-js/dc.js#829]
Hi,

I am using dc.js 2.0 alpha 5 currently. I am using the Volume vs Date barchart as the rangechart for Average Psf vs Date line graph. The interaction between the two graphs works fine for the date between Sep 01 and Sep 26. 
![good](https://cloud.githubusercontent.com/assets/9248134/5651186/35afc5e8-96e0-11e4-9229-b3e39aa47569.png)

However, the Average Psf vs Date line graph disappears when the range between Sep 01 to Sep 29 is selected.
![bad](https://cloud.githubusercontent.com/assets/9248134/5651234/95f1ce1a-96e0-11e4-9385-3d52d5964db6.png)

**Comment by gordonwoodhull** [comment]
Hi @yihaotan2012, this does look like a bug, but it will be hard to track it down without an example to reproduce it from.  Could you post a fiddle or some other way to troubleshoot the problem?

**Comment by yihaotan2012** [comment]
Hi, 

I have used Plunker to host the application. The url is http://embed.plnkr.co/aYLiLcnnP9EnncKzt6lq/preview.

To replicate the problem
1) Click on the apartment bar graph 
2) Select the date range between Sep 01 and Sep 29 

The line graph will disappear.

**Comment by gordonwoodhull** [comment]
Hmm, have you changed your app?  It looks like rangeChart is disabled on the version I'm looking at, and  parts of the series chart still disappear depending on what is selected in the volume chart.

Also, a range chart would have the same dimension as its focus chart.

Sorry, but this really looks like more of a support question than a bug in dc.js.  You have some complicated interactions going on and (at a glance; I haven't looked in-depth) it appears that data is getting lost or corrupted, rather than there being a bug in dc.js.

You'll want to put a breakpoint on the redraw functions of the various charts and see what data `group.all()` returns and whether it makes sense.

The issue tracker is for reporting bugs and making enhancement requests,  not for general support questions. Please ask on [Stack Overflow](stackoverflow.com) with the dc.js tag, or on [the user group](https://groups.google.com/forum/?fromgroups=#!forum/dc-js-user-group), and we will be glad to help you there. 

I am closing this.
