### ISSUE TITLE
Using a date range to tell if object is in the time scale

### ISSUE THREAD

**Issue by daisymarie128** [dc-js/dc.js#853]
Hi,

My data includes a a start date and end date value for each item.
ie. 
    {
       name : name,
       startDate: "22/3/12",
       endDate: "30/8/13"
     }

I'm using a line graph with brushing enabled.
Which only works for a start date. So all my other charts are missing data.
Is there a way I can check if the object is "relevant" to the selected dates in the brush ( if startDate < brush.extent[0] && endDate < brush.extent[1] ) ??

or also can this mayb work with a rowchart?
like this example http://bl.ocks.org/bunkat/2338034

Also this is a link to my old stackoverflow with more info of my data I have to work with and my problem. http://stackoverflow.com/questions/28038781/using-a-date-range-as-the-dimension-filter-through-objects-within-a-date-rang

Thanks

**Comment by gordonwoodhull** [comment]
Sorry, I did see your question in the other places but haven't responded yet because it's not an easy one. To do intervals in the most efficient way requires a special data structure called an interval tree. 

However I think there is a less efficient solution; I just haven't gotten to try it yet.

The issue tracker is not for general support questions, and I don't think this is in scope for a feature request, so I'm closing this. I hope to respond on SO soon.

**Comment by gordonwoodhull** [comment]
That's a very cool example btw!
