### ISSUE TITLE
dc.min.js.map 404 (Not Found)

### ISSUE THREAD

**Issue by adriangibbons** [dc-js/dc.js#866]
![404](https://cloud.githubusercontent.com/assets/10218647/6428884/35149dca-bfee-11e4-8db3-a3fa2e2915b4.png)

```htm
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="js/crossfilter.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/dc/1.7.3/dc.min.js"></script>
```

No 404 error if I use ```<script src="http://cdnjs.cloudflare.com/ajax/libs/dc/1.7.3/dc.js"></script>``` instead of the minified version.

The crossfilter issue is there in both cases, though this is probably because I haven't had experience of this before either.

**Comment by gordonwoodhull** [comment]
Good point, we probably need to check in the source maps along with the modified source. I have been seeing a lot of this lately, so I wonder if Chrome had gotten more proactive about downloading those.

As for the crossfilter errors, looks like perhaps you have a corrupted copy of crossfilter.min.js? Does it help if you use

https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.11/crossfilter.min.js

instead?

**Comment by gordonwoodhull** [comment]
That's @adriangibbons.

**Comment by adriangibbons** [comment]
Cheers @gordonwoodhull - I hadn't found the crossfilter CDNJS. It was that the file hadn't downloaded properly. I've downloaded again and crossfilter works fine now. Getting my head around these great tools - steep learning curve!

**Comment by gordonwoodhull** [comment]
Thanks. Yes, it is steep, but worth it.

And is the error about the .map file harmless in your app? I still want to fix it, because it breaks debuggability.

**Comment by adriangibbons** [comment]
It doesn't seem to have any impact, but I am really only doing crude examples/prototypes at the moment. Cheers

**Comment by lfdversluis** [comment]
Damn, just as I discovered DC I run into this issue. Is there any (quick) fix for it? I am using d3 now but working with 20k points in a scatterplot makes things slow, hence I found DC.

**Comment by gordonwoodhull** [comment]
@lfdversluis, as noted above, this error is not the root of your problem. Something else is crashing and then the debugger is trying to load the .map debugger file.

I'll make sure the file gets into the next beta release. To enable debugging now, simply use the non-minified dc.js instead.

**Comment by gordonwoodhull** [comment]
I should mention (as you've probably figured out) that dc.js won't automatically solve plot performance problems. You will have to aggregate in order to plot that many points using anything DOM/SVG based, and crossfilter/dc help with that, but just converting over directly won't. If you're determined to plot every one of those 20k points, you should look for something canvas-based.

**Comment by lfdversluis** [comment]
Thanks for your replies. I managed to get rid of the error, thanks :+1: As for the amount of points, yes all of them have to be plotted. Basically they are 20k genes located in the brain spatially represented by an x and y coordinate after some pre-processing. You should be able to select all or a subset of them. Based on this selection some parts of the brain (a svg that I yet have to receive) should emit lighten up (the more genes inside a part, the brighter).

As I am not that experienced with graph (and visualizing in general), could you give me a pointer to a canvas-based approach? I will definitely take a look at it then.

**Comment by gordonwoodhull** [comment]
I'm surprised that [a google search](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=d3%20canvas%20scatter) only brings up one canvas-based d3 scatterplot. I thought [this explanation](http://bocoup.com/weblog/d3js-and-canvas/) was quite cogent. However, it doesn't get quite all the way to a scatter plot and I haven't tried it myself. 

You'll probably want low opacity in order to see so many points. [This](http://stackoverflow.com/questions/2359537/how-to-change-the-opacity-alpha-transparency-of-an-element-in-a-canvas-elemen) seems like a helpful post on that.

If you have any luck, please comment on the related issue #811.
