### ISSUE TITLE
misleading (?) variable name in NASDAQ 100 (stock.js) example

### ISSUE THREAD

**Issue by espinielli** [dc-js/dc.js#868]
While studying the ([great] annotated) NASDAQ 100 example I was wondering whether `absGain` as computed for the [`yearlyPerformanceGroup`](https://github.com/dc-js/dc.js/blob/develop/web/stock.js#L71-L106) is a wrong name or uses a wrong formula.
The name says `abs` but it is calculated without any `abs` as in [line 75](https://github.com/dc-js/dc.js/blob/develop/web/stock.js#L75)

```javascript
            p.absGain += v.close - v.open;
```

A similar consideration could be made for `fluctuation`...

```javascript
           p.fluctuation += Math.abs(v.close - v.open);
```

**Comment by gordonwoodhull** [comment]
Thanks @espinielli, I have wondered about these things myself. My guess (I'm not the original author) is that, since dc.js grew out of a demo into an overnight success, there may never have been time to think these things through.

Any suggestions/patches are welcome here. 

Do you also see problems in the displayed titles and labels, or just in the code?

**Comment by espinielli** [comment]
Gordon,
I think the formula is correct, I was just misled by the _abs_.
`absGain` is the `cumulativeGain` (or Loss if negative)...I know little and would really like to find some pointer to some literature explaining the relevant indexes...(I tried few searches but nothing really satisfied my curiosity).
