### ISSUE TITLE
Font color for numberDisplay chart

### ISSUE THREAD

**Issue by Teo0uz** [dc-js/dc.js#913]
Hello,
I was wondering if there is a way to set the font color for number display chart to depend of the value of the "%number". For example the color of the text should be in green if the value is positive and red if negative.
I am sorry if my question is not clear or has already been answered.
Thank you in advance.

**Comment by AlanKavanagh** [comment]
It's not really something you should do directly with dc. Perhaps create a on('postRender') function to check the value and assign a styling based on this?

**Comment by gordonwoodhull** [comment]
I agree with @AlanKavanagh, what we used to call a "renderlet" should work fine here. A "pretransition hook" (#806) will be even better, because you might see a delay before the color is applied with a postRender or renderlet.

I'll close this, but please ask [on Stack Overflow](stackoverflow.com) with the dc.js tag, or [on the user group](https://groups.google.com/forum/?fromgroups=#!forum/dc-js-user-group) if you can't get it to work.
