### ISSUE TITLE
using aggregated data in data table

### ISSUE THREAD

**Issue by yetanotherion** [dc-js/dc.js#927]
Hello to all,

Let's take an example of 
- data = list of cars.
- car an object with attributes ("brand", "price_sold", "date_sold", "country_sold").

I'd like to display a "ranking" table that sorts the brands, from the more to the less sold.
Thanks to the group and sortBy functions, I'm currently able to make a table that displays something like
- most_sold_brand
 - ...
 - most_sold_brand, price_sold_i, date_sold_i, country_sold_i
 - ...
- second_most_sold_brand
 - ...
 - second_most_sold_brand, price_sold_j, date_sold_j, country_sold_j
 - ...
- ...

This table is however hard to read for ranking purposes, as all the *_i, *_j should be filtered manually
to have the ranking information.

What would be nice, would be to have:
- a table, like
 - most_sold_brand, number_of_most_sold_brand_cars_sold 
 - second_most_sold_brand, number_of_second_most_sold_brand_cars_sold
 - ...
- that is still refreshed by the different dimension selections performed in other charts (which I find by the way, to be an awesome feature :))

I currently don't manage to implement that, as the group in table does not 
support groups created by means of the dimension.group().reduce(add, del, init) pattern.

Do you have any suggestions on how to do so ?

**Comment by AlanKavanagh** [comment]
If I am understanding you correctly then you just want to remove the headings? Why not  add a postRender event which  gets all sub  elements with class .dc-table-label and removes them? Also this is more suited for StackOverflow than the issues since it is a question not an issue with the library. Hope that helps.

**Comment by gordonwoodhull** [comment]
@yetanotherion, my understanding of the request is to use a group instead of a dimension for the data for the data table. Because you want reduced values in the cells instead of raw rows.

I believe this is already supported, by accident. The coupling between dc and crossfilter is very light, so the data table is just calling `.all()` and `.top(N)` on the dimension and this also works with a group.

See this PR which depends on this: https://github.com/dc-js/dc.js/pull/697

In fact, the data table does not use "groups" like any other dc chart - instead it takes a `group` *function* which creates the values to nest by.

I delayed in answering because I wanted to create an example and update the documentation, but I don't have time at the moment. 

Could you please try this out and report if it works? (And if you are very kind, post a simple example.)

**Comment by gordonwoodhull** [comment]
Not helpful to OP but just to create the link, here's an equivalent issue on crossfilter, really a documentation issue here: https://github.com/square/crossfilter/issues/150

**Comment by gordonwoodhull** [comment]
More notes for myself or other maintainers.

The odd group function is documented in a comment in the stock example and nowhere else.

https://github.com/dc-js/dc.js/blob/develop/web/stock.js#L453-L458

It could be documented in the way that the special `.group()` is documented for the data count widget (but note the vague link generated, and the missing dots on the other data count member documentation).

https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#groupgroupall---mandatory

**Comment by yetanotherion** [comment]
Thanks ! It works indeed, as soon as:
- the .group() is defined, and returns the same value for all elements
- the .order() is defined & defined to something else than the default
value which seems to be either d3.ascending or descending.
(a method that is undefined for .reduce()-d dimension groups is called
else).

Where would you like that I write an example that illustrates this ?


2015-04-30 0:15 GMT+02:00 Gordon Woodhull <notifications@github.com>:

> More notes for myself or other maintainers.
>
> The odd group function is documented in a comment in the stock example and
> nowhere else.
>
> https://github.com/dc-js/dc.js/blob/develop/web/stock.js#L453-L458
>
> It could be documented in the way that the special .group() is documented
> for the data count widget (but note the vague link generated, and the
> missing dots on the other data count member documentation).
>
>
> https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#groupgroupall---mandatory
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dc-js/dc.js/issues/927#issuecomment-97603406>.
>



-- 
Ion

**Comment by gordonwoodhull** [comment]
Great! If you can, please create a PR to add the example to web/examples [which gets deployed here](http://dc-js.github.io/dc.js/examples/).

**Comment by yetanotherion** [comment]
https://github.com/dc-js/dc.js/pull/929

I'm not sure of the "table-on-aggregated-data", name
 and my editor added a newline to the index.html (did not manage to remove
it for now).



2015-04-30 19:53 GMT+02:00 Gordon Woodhull <notifications@github.com>:

> Great! If you can, please create a PR to add the example to web/examples which
> gets deployed here <http://dc-js.github.io/dc.js/examples/>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dc-js/dc.js/issues/927#issuecomment-97897342>.
>



-- 
Ion

**Comment by gordonwoodhull** [comment]
Thanks! That's fine, the index is generated anyway.

**Comment by gordonwoodhull** [comment]
Documented in #929
