### ISSUE TITLE
capped mixin shouldn't use .top(N)

### ISSUE THREAD

**Issue by alan-unravel** [dc-js/dc.js#934]
When using ordering and cap on a row chart I would assume the top-n values would be included in the cap but instead the values are takes in initial order from the grouping and then orders the result.

**Comment by alan-unravel** [comment]
This issue can be prevented by using a '.order' function on your group before passing it to your dc chart and using chart.cap as usual.

**Comment by gordonwoodhull** [comment]
Hi @alan-unravel. This is something @blairn and I were discussing on gitter. 

I consider it somewhat of a design bug. 

What happened here is that originally the capped charts just used `group.order` and `group.top`, but then
 1. `.all()` still needed to be called in order to fill in the Others, so the efficiency is lost
 2. We introduced `chart.ordering` because `group.order` only has access to the value, not the key - so this is also confusing.

Since `chart.ordering` is strictly more powerful, and using `group.top()` is kind of a blemish on the API, (especially for folks who don't use crossfilter or who use fake groups), it would probably be better just to always use `.all()` and `chart.ordering`. I'd like to hear more opinions on this, though.

**Comment by alan-unravel** [comment]
I think that would make alot more sense!

**Comment by gordonwoodhull** [comment]
I've noticed another odd usage of `.top(N)` in the bubble mixin. This is presumably in order to sort the data so that smaller bubbles will display on top of larger bubbles, but it won't work in general, because the bubble radius can be based on anything. 

We have `sortBubbleSize` for this, but it should be moved up into the mixin, and this should revert to `.all()`.

Another silently breaking change, fun!

**Comment by gordonwoodhull** [comment]
Finally, `group.top(1)` is also used in the number display, when a group instead of a groupAll is passed for the `.group()` parameter. It should be backward-compatible to default
```js
_chart.ordering(function (kv) { return kv.value; });
```

and take the maximum of `group.all()` according to the ordering, so I'm implementing this in 2.1.2
