### ISSUE TITLE
scatter plot brushing - resizeFiltered

### ISSUE THREAD

**Issue by Sumbera** [dc-js/dc.js#938]
when brushing, only resize (path) changes on symbols, this is not consistent with other graphs that usually grey-out filtered-out elements. 

would be great to have a chance to set color of filtered/non-filtered symbols on scatter plot, for example by extending resizeFiltered function with fill attribute :

       function resizeFiltered(filter) {
        var symbols = _chart.selectAll('.chart-body path.symbol').each(function (d) {
            this.filtered = filter && filter.isFiltered(d.key);
        });

        dc.transition(symbols, _chart.transitionDuration()).attr('d', _symbol)
                                                           .attr('fill', _chart.getColor); // --add this 
    }

**Comment by gordonwoodhull** [comment]
Yeah. Also, why do the selected ones get smaller instead of larger?

**Comment by Sumbera** [comment]
this is another issue, var _highlightedSize = 5;  is set up by default (so if user code spec symbol large than this it will go smaller).  As initial default it could be specified like this: 

     var _highlightedSize = _symbolSize-2;

btw,  _chart.highlightedSize  could  accept function too

**Comment by gordonwoodhull** [comment]
@PBrockman, here is the issue you were describing.

I added `.excludedSize()`, .excludedColor()` and `.excludedOpacity()` to make the behavior more direct and customizable. It still defaults to making the non-filtered ("excluded") points smaller.

"Highlighted" and "filtered" used to be sort of the same thing, which didn't make sense, because when nothing is filtered, it shouldn't all be highlighted. I consider that a bug, so I'm okay with breaking the old behavior there.

I also thought `hiddenSize` was kind of a dumb name, so I've aliased it to `emptySize`.

The logic was a bit too complicated (writing special flags to the DOM elements instead of just running the filter at the beginning of drawing), so I made it somewhat better. (It could still be simplified around highlighting, which now means just from the legend, but I left that untouched.)
