### ISSUE TITLE
Promises with DC.js

### ISSUE THREAD

**Issue by ddxtreme** [dc-js/dc.js#947]
Hi all,

I'm trying to "refactor" the DC.js in order to accept promises when render charts.
Imagine the scenario where you construct a custom function that when DC.js calls group.top(100), instead of returning the array of data and update the chart, my custom function returns a promise.

When the promise is resolved then the dc would update the chart. My aim is to "async" the charts. Can someone point me the right direction to do it? Can the "filter" action in Dc.js run async and then updates each chart with the data when the data is ready?

The problem is if you have a long "pre-processing" the UI will just hangout until it completes.

Thanks

**Comment by awjreynolds** [comment]
You should really be asking this in the dc-js-user-group@googlegroups.com

**Comment by gordonwoodhull** [comment]
Yeah, this is more of a support question for the user question or with the dc.js tag on Stack Overflow. Although there could be a feature request in this, you'll probably find a better workaround on your own side.

I think most people structure their code so that `.top()` is quick but the work is done asynchronously and redrawAll doesn't happen until the data is ready. Let's continue the conversation elsewhere.
