### ISSUE TITLE
Unset colorCalculator function for a heatmap

### ISSUE THREAD

**Issue by amergin** [dc-js/dc.js#957]
Can color functionality be toggled in a heatmap by unsetting the corresponding color function? Example: I want to be able to toggle between a linear scale (```d3.scale.linear().domain([-1, 0, 1])..range(['blue', 'white', 'red'])```) and a custom scale that is not linear ('stretched') by computing a color in a `colorCalculator` function. `$scope.heatmap` holds the chart. The toggling is handled by the below code:

```javascript
function toggle () {
  var mode = $scope.window.extra().colorScaleMode;
  $scope.window.extra()['colorScaleMode'] = (mode == 'linear') ? $scope.doStretch() : $scope.doLinear();
  $scope.heatmap.render();
}

$scope.doLinear = function() {
  $scope.heatmap.colorCalculator(undefined);
  $scope.heatmap.colors($scope.colorScale.linear.scale);
  $scope.heatmap.colorAccessor($scope.colorScale.linear.accessor);
  return 'linear';
};

$scope.doStretch = function() {
  $scope.heatmap.colorAccessor(undefined);
  $scope.heatmap.colorCalculator($scope.colorScale.stretch.calculator);
  return 'stretch';
};
```
What I'm seeing now on 'stretch' is that the colors are applied as should be. When toggled to 'linear', the cells are shown in black and `colorAccessor` is not called even though it's a proper function. I also tried `null` in place of `undefined`. 

Any ideas?

**Comment by gordonwoodhull** [comment]
I haven't looked into your issue closely, but currently the only way to reset the color accessor is to call

```{javascript}
chart.colorAccessor(function(d) { return chart.keyAccessor()(d); })
```

I.e. using (almost) the original default value defined in the color mixin:
https://github.com/dc-js/dc.js/blob/develop/src/color-mixin.js#L12

Does this help? Resetting with `null` does sound reasonable, but it would be some work, since all the APIs currently just lose the default value once you set them.

**Comment by gordonwoodhull** [comment]
I also wouldn't mess with the `colorCalculator` as it's basically just a synonym for `getColor`, which usually does what you want (applies the color scale to the accessor value).

https://github.com/dc-js/dc.js/blob/develop/src/color-mixin.js#L125

IMO it should be deprecated. It used to have a different function before we standardized on a more d3-idiomatic way of dealing with colors.

**Comment by amergin** [comment]
The reason to use `colorCalculator` is a bit tricky; the used color range requires knowledge of the min/max values and I didn't see how this could be written in a custom d3 interpolator. The current implementation for my use is [here](https://gist.github.com/amergin/77d81f53f509bbc35e21). Then again the color could also be stored within the `d`...

Anyways, using your suggestion I just stored the initial functions of `colorAccessor` and `colorCalculator` and restore them when necessary; color toggling now works. Thanks!

**Comment by gordonwoodhull** [comment]
I see. Yes, a color calculator is perhaps more flexible because it is lower-level.

Thanks @amergin for sharing your code, and glad we got this working!

**Comment by gordonwoodhull** [comment]
@amergin, I was fixing the docs for `colorCalculator` and I still think it should be deprecated, so I'm going ahead with that for v2.0. 

I'm pretty certain that a color accessor and color scale will cover your use case. I don't think it can get more general. It's quite common for d3 color scales to use the min/max values - so you'd just define a custom d3 scale instead of replacing the whole calculator.

Please open another issue if you dispute this. Thanks!
